### ISSUE TITLE
no schedule for ib 4 courses

### ISSUE THREAD

**Issue by JulianWagner91** [Fachschaft07/fs-android-app#58]
Not able to receive schedule for an ib 4 course.
Maybe it is the same problem as last semester?

**Comment by jqbbq** [comment]
This was probably due to an parsing issue with the FK10 Timetable inside the REST Service. We just update the Service and for me it seems the issue is resolved.
 
@JulianWagner91, can you please check and give feedback?

**Comment by JulianWagner91** [comment]
no i can see the courses. But by the time I want to choose a course from Pasing like Bilanzierung than the app crashes every time I go to the schedule. 
I have to delete all data from this app via the all-installed-apps from android.
